// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraceyDawley.Models;

#nullable disable

namespace TraceyDawley.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231024065420_ initial_0")]
    partial class initial_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TraceyDawley.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(355)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = "00000000000",
                            CreatedAt = new DateTime(2023, 10, 24, 11, 54, 20, 480, DateTimeKind.Local).AddTicks(8745),
                            Email = "superadmin@gmail.com",
                            FirstName = "Super",
                            IsActive = 1,
                            LastName = "Admin",
                            MiddleName = "",
                            Password = "123",
                            Role = 0,
                            UserId = new Guid("2c516c66-a794-4e14-8a0c-4ccdf00cfbc0")
                        },
                        new
                        {
                            Id = 2,
                            Contact = "00000000000",
                            CreatedAt = new DateTime(2023, 10, 24, 11, 54, 20, 480, DateTimeKind.Local).AddTicks(8767),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            IsActive = 1,
                            LastName = "",
                            MiddleName = "",
                            Password = "123",
                            Role = 1,
                            UserId = new Guid("9d23a508-6a7c-4881-b231-c37c757cacfe")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
